### ISSUE TITLE
some questions about datasets

### ISSUE THREAD

**Issue by CRISZJ** [maxorange/voxel-dcgan#7]
Do you have any result of input data and output data, thanks

**Comment by maxorange** [comment]
Three output data are in `out` folder, but I don't have input data. Sorry. We have to write code for saving input data.

**Comment by CRISZJ** [comment]
> Three output data are in `out` folder, but I don't have input data. Sorry. We have to write code for saving input data.

thanks for your reply, your project's input and output file's type are also *.binvox, is it right? And I also 
meet this problem as follows:
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    model.optimize(z, x)
  File "/home/voxel-dcgan/model.py", line 105, in optimize
    self.sess.run(self.optD, feed_dict=fd)
  File "/home/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1093, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/anaconda3/envs/tensorflow/lib/python2.7/site-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.

**Comment by maxorange** [comment]
Yes. Output file type is binvox. To reproduce the error on my environment, cloud you tell me tensorflow version? Maybe, tensorflow==1.15 works.

**Comment by CRISZJ** [comment]
> Yes. Output file type is binvox. To reproduce the error on my environment, cloud you tell me tensorflow version? Maybe, tensorflow==1.15 works.

the version I used is tensorflow1.14,python2.7.Could you please tell me your enviroments? include the version of tensorflow ,  numpy ,and so on?
look forward to your reply

**Comment by maxorange** [comment]
I tested tensorflow 1.15 with python 2.7.
This is output of `pip list`:
```
Package              Version    
-------------------- -----------
absl-py              0.9.0      
astor                0.8.1      
backports.weakref    1.0.post1  
enum34               1.1.6      
funcsigs             1.0.2      
functools32          3.2.3.post2
futures              3.3.0      
gast                 0.2.2      
google-pasta         0.1.8      
grpcio               1.26.0     
h5py                 2.10.0     
Keras-Applications   1.0.8      
Keras-Preprocessing  1.1.0      
Markdown             3.1.1      
mock                 3.0.5      
numpy                1.16.5     
opt-einsum           2.3.2      
pip                  19.3.1     
protobuf             3.11.2     
setuptools           42.0.2     
six                  1.13.0     
tensorboard          1.15.0     
tensorflow           1.15.0     
tensorflow-estimator 1.15.1     
termcolor            1.1.0      
Werkzeug             0.16.0     
wheel                0.33.6     
wrapt                1.11.2
```

**Comment by CRISZJ** [comment]
ok,thanks very much, it's the problem of enviroment, do you konw this errors? it as follows:
ValueError: Cannot feed value of shape (1, 32, 32, 32, 1) for Tensor u'x0:0', which has shape '(64, 32, 32, 32, 1)'

**Comment by maxorange** [comment]
We need to change batch_size to 1 in config.py
https://github.com/maxorange/voxel-dcgan/blob/master/config.py

**Comment by CRISZJ** [comment]
> We need to change batch_size to 1 in config.py
> https://github.com/maxorange/voxel-dcgan/blob/master/config.py
I've tried, But it not work. The error is :
ValueError: Cannot feed value of shape (1, 256, 256, 256, 1) for Tensor u'x0:0', which has shape '(1, 32, 32, 32, 1)'

**Comment by CRISZJ** [comment]
do you have solved it?

**Comment by maxorange** [comment]
Sorry for late. We can solve it by setting `nvx` to 256 in config.py

**Comment by CRISZJ** [comment]
> Sorry for late. We can solve it by setting `nvx` to 256 in config.py

Solved it . thanks
